package org.example.cafepos;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class DashboardPDFGenerator {

    public static void generateDashboardReport(
            int totalCustomers,
            double todayIncome,
            double totalIncome,
            int totalSales,
            String filePath) throws IOException {

        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage();
            document.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                // Set up fonts
                PDType1Font fontBold = PDType1Font.HELVETICA_BOLD;
                PDType1Font fontRegular = PDType1Font.HELVETICA;

                // Add title
                contentStream.beginText();
                contentStream.setFont(fontBold, 18);
                contentStream.newLineAtOffset(100, 700);
                contentStream.showText("Cafe POS Dashboard Report");
                contentStream.endText();

                // Add date
                contentStream.beginText();
                contentStream.setFont(fontRegular, 12);
                contentStream.newLineAtOffset(100, 670);
                contentStream.showText("Generated on: " + LocalDate.now().format(DateTimeFormatter.ISO_DATE));
                contentStream.endText();

                // Add report data
                contentStream.beginText();
                contentStream.setFont(fontBold, 14);
                contentStream.newLineAtOffset(100, 630);
                contentStream.showText("Dashboard Summary");
                contentStream.endText();

                // Add line separator
                contentStream.moveTo(100, 620);
                contentStream.lineTo(500, 620);
                contentStream.stroke();

                // Add metrics
                int yPosition = 590;
                addMetric(contentStream, "Total Customers:", String.valueOf(totalCustomers), 100, yPosition);
                yPosition -= 30;
                addMetric(contentStream, "Today's Income:", String.format("LKR %.2f", todayIncome), 100, yPosition);
                yPosition -= 30;
                addMetric(contentStream, "Total Income:", String.format("LKR %.2f", totalIncome), 100, yPosition);
                yPosition -= 30;
                addMetric(contentStream, "Total Products Sold:", String.valueOf(totalSales), 100, yPosition);

                // Add footer
                contentStream.beginText();
                contentStream.setFont(fontRegular, 10);
                contentStream.newLineAtOffset(100, 50);
                contentStream.showText("Generated by Cafe POS System");
                contentStream.endText();
            }

            // Save the document
            document.save(filePath);
        }
    }

    private static void addMetric(PDPageContentStream contentStream,
                                  String label, String value,
                                  float x, float y) throws IOException {
        contentStream.beginText();
        contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
        contentStream.newLineAtOffset(x, y);
        contentStream.showText(label);
        contentStream.endText();

        contentStream.beginText();
        contentStream.setFont(PDType1Font.HELVETICA, 12);
        contentStream.newLineAtOffset(x + 150, y);
        contentStream.showText(value);
        contentStream.endText();
    }
}